replicaCount: 3

image:
  repository: tylermac92/self-healing-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

probes:
  readiness:
    path: /readyz
    initialDelaySeconds: 5
    periodSeconds: 5
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10

pdb:
  enabled: true
  minAvailable: 1

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

labels:
  app: self-healing

podAnnotations: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
